# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e950a20240a7fb9d912124d26ef146426a18f01fa693c4c95a068f297976bef200c629898000332846387645e94229c9569004af1e1af81d628b122264943139

test:
  secret_key_base: c042638feb892c234e97fd2245deca37737bee1f41eec5bd03adeba3443f4a4204ec824f46a44cdd55eb33c36e72591a584eaa1aebfe4150c6e02afb453b9326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
